version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nodejs_version: 6
install:
- ps: Install-Product node $env:nodejs_version
before_build:
- cmd: nuget restore .\src\Sitecore.Js.Presentation.sln
after_build:
- node --version
- npm --version
- cd .\sample\front-end 
- npm i
- npm run server:dev
- 7z a Sitecore.Js.Presentation.Sample.zip %APPVEYOR_BUILD_FOLDER%\sample\front-end\dist\
- cd %APPVEYOR_BUILD_FOLDER%
artifacts:
- path: '**\Sitecore.Js.Presentation.Sample.zip'
  name: 'UI Sample Package'
  type: zip
- path: 'sample\sc-packages\Sitecore.Js.Presentation.Sample.Master.update'
  name: 'Sitecore Update Package'
  type: zip
build:
  project: .\src\Sitecore.Js.Presentation.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: Environment
  name: NuGet.org
  on:
    branch: master
- provider: Environment
  name: GitHub Releases Sitecore.Js.Presentation
  on:
    branch: master
cache:
  - src\packages -> src\**\packages.config        # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - sample\front-end\node_modules -> sample\front-end\packages.json   # local npm modules
  - '%APPDATA%\npm-cache'                     # npm cache